# Generated by Django 3.2.9 on 2021-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='email',
        ),
        migrations.AddField(
            model_name='link',
            name='instagram',
            field=models.CharField(default='instagramuser', max_length=400),
        ),
        migrations.AddField(
            model_name='link',
            name='reddit',
            field=models.CharField(default='reddituser', max_length=400),
        ),
        migrations.AddField(
            model_name='link',
            name='youtube',
            field=models.CharField(default='youtubeuser', max_length=400),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tw_link',
            field=models.CharField(default='mytweetlink', max_length=400),
        ),
    ]
