# Generated by Django 3.2.9 on 2022-01-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211228_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Ethaddress',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Instagram',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Reddit',
        ),
        migrations.DeleteModel(
            name='Telegram',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.DeleteModel(
            name='Youtube',
        ),
        migrations.AddField(
            model_name='user',
            name='payload',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
