# Generated by Django 3.2.9 on 2022-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refs',
            field=models.CharField(default='NO_REFERRAL', max_length=50),
        ),
    ]
