# Generated by Django 3.2.9 on 2022-01-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_verify_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='referal',
        ),
        migrations.AddField(
            model_name='link',
            name='referral',
            field=models.IntegerField(default=0),
        ),
    ]
