# Generated by Django 3.2.9 on 2022-01-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220117_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='referral',
            field=models.IntegerField(),
        ),
    ]
