# Generated by Django 3.2.9 on 2022-01-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_link_refe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='refe',
        ),
        migrations.AlterField(
            model_name='link',
            name='referral',
            field=models.IntegerField(default=0),
        ),
    ]
